name: app_8april_2022
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  badges: ^2.0.2
  cloud_firestore: 3.1.12
  cupertino_icons: ^1.0.2
  firebase_auth: 3.3.14
  firebase_core: 1.14.1
  firebase_storage: 10.2.12
  flutter_login_facebook: 1.4.1
  get: 4.6.1
  get_storage: 2.0.3
  google_sign_in: 5.3.0
  http: ^0.13.4
  loading_animation_widget: 1.1.0+3
  path: 1.8.0
  sliding_clipped_nav_bar: 3.1.0
  sqflite: 2.0.2+1
  uuid: 3.0.6
  logger: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/fonts/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  uses-material-design: true

