// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd4mgKxB8zH7oZUIWttwpDLVeV-XfZnqI',
    appId: '1:856893842551:android:807dff5574f43cae799272',
    messagingSenderId: '856893842551',
    projectId: 'shop-app-76b4d',
    storageBucket: 'shop-app-76b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_cJemeDabfYGaMk4e2RbfFB0TVaT5pAo',
    appId: '1:856893842551:ios:0d919a3547742c94799272',
    messagingSenderId: '856893842551',
    projectId: 'shop-app-76b4d',
    storageBucket: 'shop-app-76b4d.appspot.com',
    iosClientId: '856893842551-1pamhsql2usiegvejiti3ri54o3t2o07.apps.googleusercontent.com',
    iosBundleId: 'com.purboindra.sa',
  );
}
